management:
  tracing:
    sampling:
      probability: 1
    baggage:
      correlation:
        fields:
          - 'abc'
      local-fields:
        - 'abc'
      remote-fields:
        - 'abc'

spring:
  application:
    name: demo-tracing
  reactor:
    context-propagation: auto

logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  include-application-name: false
  include-application-group: false