management:
  tracing:
    baggage:
      local-fields: &sleuth_keys
        - abc
      correlation:
        fields: *sleuth_keys

spring:
  application:
    name: demo-tracing
  reactor:
    context-propagation: auto

logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
    dateformat: HH:mm:ss.SSS
  include-application-name: false
  include-application-group: false